### ISSUE TITLE
Back button/action from one of the modes

### ISSUE THREAD

**Issue by ioana-chiorean** [debloper/repwho#1]
Currently i did not find a way to go back after choosing one of the modes.

**Comment by debloper** [comment]
Yes, so far reloading is the only solution. Needs fixing.

**Comment by ioana-chiorean** [comment]
will be waiting..

**Comment by AlexLakatos** [comment]
this has been fixed by pull request #5 . You can close the issue.

**Comment by debloper** [comment]
Thanks - I should've added `fixes #1` in the merge commit message.
