### ISSUE TITLE
Leader Board

### ISSUE THREAD

**Issue by ioana-chiorean** [debloper/repwho#2]
I think it will be fun to give a certain amount of point for guessing / a minus amount for wrong answer and to have a total points gained - can be further compared to fellow Reps.

**Comment by debloper** [comment]
Good suggestion, but for that the app will require read/write access to a DB/persistent-storage of some sort.
I'll try & get hold of mozillareps.org's infra for that, if possible.

**Comment by ioana-chiorean** [comment]
Black hole ?

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢 
Will reopen if this will restart! 🍀
