### ISSUE TITLE
Log In - address used in ReMo portal

### ISSUE THREAD

**Issue by ioana-chiorean** [debloper/repwho#3]
- LederBoard
  -Top with other friends etc.

**Comment by debloper** [comment]
This should be blocked by #2.
It should be possible to integrate persona.

**Comment by ioana-chiorean** [comment]
Maybe Pierros can help with persona as we have it on Reps portal.

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢 
Will reopen if this will restart! 🍀
